# Base image
FROM node:22-alpine3.19

# Create app directory
WORKDIR /usr/src/app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY --chown=node:node package*.json ./

# Install app dependencies using the `npm ci` command instead of `npm install`
RUN npm ci

# Bundle app source
COPY --chown=node:node . .

# Use the node user from the image (instead of the root user)
USER node

CMD ["sh", "-c", "npx wait-on tcp:postgres:5432 && npm run migration:generate && npm run migration:run && npm run start:dev"]